-- Table to store lost items
CREATE TABLE lost_items
(
    id              BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name       VARCHAR(255)    NOT NULL,
    quantity        INTEGER         NOT NULL,
    place           VARCHAR(255)    NOT NULL,
    UNIQUE (item_name, place)
);

-- Table to store user information
CREATE TABLE users
(
    id              VARCHAR(255)    PRIMARY KEY UNIQUE,
    password        VARCHAR(255)    NOT NULL,
    name            VARCHAR(255)    NOT NULL
);

-- Table to store roles
CREATE TABLE roles
(
    id              BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255)    NOT NULL UNIQUE
);

-- Relational table to store user roles
CREATE TABLE user_roles
(
    user_id         VARCHAR(255)    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id         BIGINT          NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

-- Table to store claims on lost items
CREATE TABLE claims
(
    id              BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         VARCHAR(255)    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    lost_item_id    BIGINT          NOT NULL REFERENCES lost_items (id) ON DELETE CASCADE,
    quantity        INTEGER         NOT NULL,
    UNIQUE (user_id, lost_item_id)
);

-------------------------
-- For testing purposes
-------------------------
-- Insert roles
INSERT INTO roles (name) VALUES ('ROLE_USER');
INSERT INTO roles (name) VALUES ('ROLE_ADMIN');

-- Insert users
INSERT INTO users (id, password, name) VALUES ('user1', '$2a$12$WJTOQJX.1dokM3EiZAjFF.MyCwIfHHDRmEoPxaGHITgoLk.8Pyrdm', 'User One');
INSERT INTO users (id, password, name) VALUES ('admin1', '$2a$12$1NFXR8EugAfhXcV.QCe/juJisC4pjuXIgU0gTy9T.KGIUR/WFQOda', 'Admin One');

-- Assign roles to users
INSERT INTO user_roles (user_id, role_id) VALUES ('user1', (SELECT id FROM roles WHERE name = 'ROLE_USER'));
INSERT INTO user_roles (user_id, role_id) VALUES ('admin1', (SELECT id FROM roles WHERE name = 'ROLE_ADMIN'));